repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: docformatter
        name: docformatter
        language: system
        entry: uvx docformatter
        args: ["--in-place", "--wrap-summaries", "150", "--wrap-descriptions", "150"]
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.7
    hooks:
      # Run the formatter.
      - id: ruff-format
